# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c0e736372b9cc797908ca2b518e078558729c0d8548f16115e890795a1473fed1e1e4ff461dcf769e1bf5b8bc5309e29fa593b82b171f1d2bb5c2f538320ed4

test:
  secret_key_base: 692caf7493fed4427a30fb23179186f1a48fc3e50d134261804c1c187b08c753e3e5e9bf06d50a1b80d3b87bb2b6d0b0b5ae67360ce0e5dc6b56c2e7e042b790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
